"""empty message

Revision ID: b5b76f96ed0b
Revises: c037f06c8b17
Create Date: 2017-04-28 03:07:32.002156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5b76f96ed0b'
down_revision = 'c037f06c8b17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist', sa.Column('userid', sa.String(length=80), nullable=True))
    op.drop_column('wishlist', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist', sa.Column('user', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('wishlist', 'userid')
    # ### end Alembic commands ###
