"""empty message

Revision ID: c037f06c8b17
Revises: 11ffb23bb5b9
Create Date: 2017-04-25 02:23:46.725399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c037f06c8b17'
down_revision = '11ffb23bb5b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'wishlist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('wishlist', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
