"""empty message

Revision ID: ef31163da389
Revises: 98bdf16c121e
Create Date: 2017-04-25 00:03:49.601072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef31163da389'
down_revision = '98bdf16c121e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('wishlist', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'wishlist')
    # ### end Alembic commands ###
